"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Denominatedoraclefactory__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "constructor",
        inputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "addAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "authorizedAccounts",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "_authorized",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "authorizedAccounts",
        inputs: [],
        outputs: [
            {
                name: "_accounts",
                type: "address[]",
                internalType: "address[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "denominatedOraclesList",
        inputs: [],
        outputs: [
            {
                name: "_denominatedOraclesList",
                type: "address[]",
                internalType: "address[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "deployDenominatedOracle",
        inputs: [
            {
                name: "_priceSource",
                type: "address",
                internalType: "contract IBaseOracle",
            },
            {
                name: "_denominationPriceSource",
                type: "address",
                internalType: "contract IBaseOracle",
            },
            {
                name: "_inverted",
                type: "bool",
                internalType: "bool",
            },
        ],
        outputs: [
            {
                name: "_denominatedOracle",
                type: "address",
                internalType: "contract IBaseOracle",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "AddAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "NewDenominatedOracle",
        inputs: [
            {
                name: "_denominatedOracle",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "_priceSource",
                type: "address",
                indexed: false,
                internalType: "address",
            },
            {
                name: "_denominationPriceSource",
                type: "address",
                indexed: false,
                internalType: "address",
            },
            {
                name: "_inverted",
                type: "bool",
                indexed: false,
                internalType: "bool",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RemoveAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "AlreadyAuthorized",
        inputs: [],
    },
    {
        type: "error",
        name: "NotAuthorized",
        inputs: [],
    },
    {
        type: "error",
        name: "Unauthorized",
        inputs: [],
    },
];
var Denominatedoraclefactory__factory = exports.Denominatedoraclefactory__factory = /** @class */ (function () {
    function Denominatedoraclefactory__factory() {
    }
    Denominatedoraclefactory__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Denominatedoraclefactory__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Denominatedoraclefactory__factory.abi = _abi;
    return Denominatedoraclefactory__factory;
}());
//# sourceMappingURL=Denominatedoraclefactory__factory.js.map