"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DoubleEndedQueue__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "error",
        name: "QueueEmpty",
        inputs: [],
    },
    {
        type: "error",
        name: "QueueFull",
        inputs: [],
    },
    {
        type: "error",
        name: "QueueOutOfBounds",
        inputs: [],
    },
];
var DoubleEndedQueue__factory = exports.DoubleEndedQueue__factory = /** @class */ (function () {
    function DoubleEndedQueue__factory() {
    }
    DoubleEndedQueue__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    DoubleEndedQueue__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    DoubleEndedQueue__factory.abi = _abi;
    return DoubleEndedQueue__factory;
}());
//# sourceMappingURL=DoubleEndedQueue__factory.js.map