"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ERC721Holder__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "onERC721Received",
        inputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
            {
                name: "",
                type: "address",
                internalType: "address",
            },
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes4",
                internalType: "bytes4",
            },
        ],
        stateMutability: "nonpayable",
    },
];
var ERC721Holder__factory = exports.ERC721Holder__factory = /** @class */ (function () {
    function ERC721Holder__factory() {
    }
    ERC721Holder__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ERC721Holder__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ERC721Holder__factory.abi = _abi;
    return ERC721Holder__factory;
}());
//# sourceMappingURL=ERC721Holder__factory.js.map