"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Erc721holder__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "onERC721Received",
        inputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
            {
                name: "",
                type: "address",
                internalType: "address",
            },
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes4",
                internalType: "bytes4",
            },
        ],
        stateMutability: "nonpayable",
    },
];
var Erc721holder__factory = exports.Erc721holder__factory = /** @class */ (function () {
    function Erc721holder__factory() {
    }
    Erc721holder__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Erc721holder__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Erc721holder__factory.abi = _abi;
    return Erc721holder__factory;
}());
//# sourceMappingURL=Erc721holder__factory.js.map