"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Factorychild__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "factory",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "error",
        name: "CallerNotFactory",
        inputs: [],
    },
    {
        type: "error",
        name: "NotFactoryDeployment",
        inputs: [],
    },
];
var Factorychild__factory = exports.Factorychild__factory = /** @class */ (function () {
    function Factorychild__factory() {
    }
    Factorychild__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Factorychild__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Factorychild__factory.abi = _abi;
    return Factorychild__factory;
}());
//# sourceMappingURL=Factorychild__factory.js.map