"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.HardcodedOracle__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "constructor",
        inputs: [
            {
                name: "_symbol",
                type: "string",
                internalType: "string",
            },
            {
                name: "_price",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getResultWithValidity",
        inputs: [],
        outputs: [
            {
                name: "_price",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_validity",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "price",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "read",
        inputs: [],
        outputs: [
            {
                name: "_value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "error",
        name: "InvalidPriceFeed",
        inputs: [],
    },
];
var HardcodedOracle__factory = exports.HardcodedOracle__factory = /** @class */ (function () {
    function HardcodedOracle__factory() {
    }
    HardcodedOracle__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    HardcodedOracle__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    HardcodedOracle__factory.abi = _abi;
    return HardcodedOracle__factory;
}());
//# sourceMappingURL=HardcodedOracle__factory.js.map