"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IAbstractVeloVaultRelayer__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "getResultWithValidity",
        inputs: [],
        outputs: [
            {
                name: "_result",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_validity",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "read",
        inputs: [],
        outputs: [
            {
                name: "_value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [
            {
                name: "_symbol",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "veloLpOracle",
        inputs: [],
        outputs: [
            {
                name: "_veloPool",
                type: "address",
                internalType: "contract IPessimisticVeloLpOracle",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "veloPool",
        inputs: [],
        outputs: [
            {
                name: "_veloPool",
                type: "address",
                internalType: "contract IVeloPool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "error",
        name: "AbstractVeloVaultRelayer_NullVeloLpOracle",
        inputs: [],
    },
    {
        type: "error",
        name: "AbstractVeloVaultRelayer_NullVeloPool",
        inputs: [],
    },
    {
        type: "error",
        name: "InvalidPriceFeed",
        inputs: [],
    },
];
var IAbstractVeloVaultRelayer__factory = exports.IAbstractVeloVaultRelayer__factory = /** @class */ (function () {
    function IAbstractVeloVaultRelayer__factory() {
    }
    IAbstractVeloVaultRelayer__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IAbstractVeloVaultRelayer__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IAbstractVeloVaultRelayer__factory.abi = _abi;
    return IAbstractVeloVaultRelayer__factory;
}());
//# sourceMappingURL=IAbstractVeloVaultRelayer__factory.js.map