"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IBeefyVaultV7__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "getPricePerFullShare",
        inputs: [],
        outputs: [
            {
                name: "_pricePerFullShare",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [
            {
                name: "_symbol",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
];
var IBeefyVaultV7__factory = exports.IBeefyVaultV7__factory = /** @class */ (function () {
    function IBeefyVaultV7__factory() {
    }
    IBeefyVaultV7__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IBeefyVaultV7__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IBeefyVaultV7__factory.abi = _abi;
    return IBeefyVaultV7__factory;
}());
//# sourceMappingURL=IBeefyVaultV7__factory.js.map