"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ichainlinkoracle__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "decimals",
        inputs: [],
        outputs: [
            {
                name: "_decimals",
                type: "uint8",
                internalType: "uint8",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "description",
        inputs: [],
        outputs: [
            {
                name: "_description",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getAnswer",
        inputs: [
            {
                name: "_roundId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "_answer",
                type: "int256",
                internalType: "int256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoundData",
        inputs: [
            {
                name: "__roundId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "_roundId",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_answer",
                type: "int256",
                internalType: "int256",
            },
            {
                name: "_startedAt",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_updatedAt",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_answeredInRound",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getTimestamp",
        inputs: [
            {
                name: "_roundId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "_timestamp",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "latestAnswer",
        inputs: [],
        outputs: [
            {
                name: "_latestAnswer",
                type: "int256",
                internalType: "int256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "latestRound",
        inputs: [],
        outputs: [
            {
                name: "_latestRound",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "latestRoundData",
        inputs: [],
        outputs: [
            {
                name: "_roundId",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_answer",
                type: "int256",
                internalType: "int256",
            },
            {
                name: "_startedAt",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_updatedAt",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_answeredInRound",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "latestTimestamp",
        inputs: [],
        outputs: [
            {
                name: "_latestTimestamp",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
];
var Ichainlinkoracle__factory = exports.Ichainlinkoracle__factory = /** @class */ (function () {
    function Ichainlinkoracle__factory() {
    }
    Ichainlinkoracle__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Ichainlinkoracle__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Ichainlinkoracle__factory.abi = _abi;
    return Ichainlinkoracle__factory;
}());
//# sourceMappingURL=Ichainlinkoracle__factory.js.map