"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Icommonactions__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "exitAllSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "exitCollateral",
        inputs: [
            {
                name: "_collateralJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_wad",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "exitSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinsToExit",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "joinSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_dst",
                type: "address",
                internalType: "address",
            },
            {
                name: "_wad",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "error",
        name: "OnlyDelegateCalls",
        inputs: [],
    },
];
var Icommonactions__factory = exports.Icommonactions__factory = /** @class */ (function () {
    function Icommonactions__factory() {
    }
    Icommonactions__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Icommonactions__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Icommonactions__factory.abi = _abi;
    return Icommonactions__factory;
}());
//# sourceMappingURL=Icommonactions__factory.js.map