"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IDenominatedOracle__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "denominationPriceSource",
        inputs: [],
        outputs: [
            {
                name: "_denominationPriceSource",
                type: "address",
                internalType: "contract IBaseOracle",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getResultWithValidity",
        inputs: [],
        outputs: [
            {
                name: "_result",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_validity",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "inverted",
        inputs: [],
        outputs: [
            {
                name: "_inverted",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "priceSource",
        inputs: [],
        outputs: [
            {
                name: "_priceSource",
                type: "address",
                internalType: "contract IBaseOracle",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "read",
        inputs: [],
        outputs: [
            {
                name: "_value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [
            {
                name: "_symbol",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "error",
        name: "DenominatedOracle_NullPriceSource",
        inputs: [],
    },
    {
        type: "error",
        name: "InvalidPriceFeed",
        inputs: [],
    },
];
var IDenominatedOracle__factory = exports.IDenominatedOracle__factory = /** @class */ (function () {
    function IDenominatedOracle__factory() {
    }
    IDenominatedOracle__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IDenominatedOracle__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IDenominatedOracle__factory.abi = _abi;
    return IDenominatedOracle__factory;
}());
//# sourceMappingURL=IDenominatedOracle__factory.js.map