"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ierc165__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "supportsInterface",
        inputs: [
            {
                name: "interfaceId",
                type: "bytes4",
                internalType: "bytes4",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
];
var Ierc165__factory = exports.Ierc165__factory = /** @class */ (function () {
    function Ierc165__factory() {
    }
    Ierc165__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Ierc165__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Ierc165__factory.abi = _abi;
    return Ierc165__factory;
}());
//# sourceMappingURL=Ierc165__factory.js.map