"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IExistingPriceOracle__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "getPrice",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "lastUpdatedBlock",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "metadata",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
];
var IExistingPriceOracle__factory = exports.IExistingPriceOracle__factory = /** @class */ (function () {
    function IExistingPriceOracle__factory() {
    }
    IExistingPriceOracle__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IExistingPriceOracle__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IExistingPriceOracle__factory.abi = _abi;
    return IExistingPriceOracle__factory;
}());
//# sourceMappingURL=IExistingPriceOracle__factory.js.map