"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Ipessimisticvelolporacle__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "getCurrentPoolPrice",
        inputs: [
            {
                name: "_pool",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "_price",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
];
var Ipessimisticvelolporacle__factory = exports.Ipessimisticvelolporacle__factory = /** @class */ (function () {
    function Ipessimisticvelolporacle__factory() {
    }
    Ipessimisticvelolporacle__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Ipessimisticvelolporacle__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Ipessimisticvelolporacle__factory.abi = _abi;
    return Ipessimisticvelolporacle__factory;
}());
//# sourceMappingURL=Ipessimisticvelolporacle__factory.js.map