"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Irewardedactions__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "exitAllSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "exitCollateral",
        inputs: [
            {
                name: "_collateralJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_wad",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "exitSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinsToExit",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "joinSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_dst",
                type: "address",
                internalType: "address",
            },
            {
                name: "_wad",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "liquidateSAFE",
        inputs: [
            {
                name: "_liquidationJob",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_cType",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "_safe",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "popDebtFromQueue",
        inputs: [
            {
                name: "_accountingJob",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_debtTimestamp",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "startDebtAuction",
        inputs: [
            {
                name: "_accountingJob",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "startSurplusAuction",
        inputs: [
            {
                name: "_accountingJob",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "transferExtraSurplus",
        inputs: [
            {
                name: "_accountingJob",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "updateCollateralPrice",
        inputs: [
            {
                name: "_oracleJob",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_cType",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "updateRedemptionRate",
        inputs: [
            {
                name: "_oracleJob",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "error",
        name: "OnlyDelegateCalls",
        inputs: [],
    },
];
var Irewardedactions__factory = exports.Irewardedactions__factory = /** @class */ (function () {
    function Irewardedactions__factory() {
    }
    Irewardedactions__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Irewardedactions__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Irewardedactions__factory.abi = _abi;
    return Irewardedactions__factory;
}());
//# sourceMappingURL=Irewardedactions__factory.js.map