"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Isettlementsurplusauctioneer__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "accountingEngine",
        inputs: [],
        outputs: [
            {
                name: "_accountingEngine",
                type: "address",
                internalType: "contract IAccountingEngine",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "addAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "auctionSurplus",
        inputs: [],
        outputs: [
            {
                name: "_id",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "authorizedAccounts",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "_authorized",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "authorizedAccounts",
        inputs: [],
        outputs: [
            {
                name: "_accounts",
                type: "address[]",
                internalType: "address[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "lastSurplusTime",
        inputs: [],
        outputs: [
            {
                name: "_lastSurplusTime",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "modifyParameters",
        inputs: [
            {
                name: "_param",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "_data",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "safeEngine",
        inputs: [],
        outputs: [
            {
                name: "_safeEngine",
                type: "address",
                internalType: "contract ISAFEEngine",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "surplusAuctionHouse",
        inputs: [],
        outputs: [
            {
                name: "_surplusAuctionHouse",
                type: "address",
                internalType: "contract ISurplusAuctionHouse",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "AddAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "AuctionSurplus",
        inputs: [
            {
                name: "_id",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "_lastSurplusAuctionTime",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "_coinBalance",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ModifyParameters",
        inputs: [
            {
                name: "_param",
                type: "bytes32",
                indexed: true,
                internalType: "bytes32",
            },
            {
                name: "_cType",
                type: "bytes32",
                indexed: true,
                internalType: "bytes32",
            },
            {
                name: "_data",
                type: "bytes",
                indexed: false,
                internalType: "bytes",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RemoveAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "AlreadyAuthorized",
        inputs: [],
    },
    {
        type: "error",
        name: "NotAuthorized",
        inputs: [],
    },
    {
        type: "error",
        name: "SSA_AccountingEngineStillEnabled",
        inputs: [],
    },
    {
        type: "error",
        name: "SSA_SurplusAuctionDelayNotPassed",
        inputs: [],
    },
    {
        type: "error",
        name: "Unauthorized",
        inputs: [],
    },
    {
        type: "error",
        name: "UnrecognizedCType",
        inputs: [],
    },
    {
        type: "error",
        name: "UnrecognizedParam",
        inputs: [],
    },
];
var Isettlementsurplusauctioneer__factory = exports.Isettlementsurplusauctioneer__factory = /** @class */ (function () {
    function Isettlementsurplusauctioneer__factory() {
    }
    Isettlementsurplusauctioneer__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Isettlementsurplusauctioneer__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Isettlementsurplusauctioneer__factory.abi = _abi;
    return Isettlementsurplusauctioneer__factory;
}());
//# sourceMappingURL=Isettlementsurplusauctioneer__factory.js.map