"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISurplusBidActions__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "exitAllSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "exitCollateral",
        inputs: [
            {
                name: "_collateralJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_wad",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "exitSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_coinsToExit",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "increaseBidSize",
        inputs: [
            {
                name: "_surplusAuctionHouse",
                type: "address",
                internalType: "address",
            },
            {
                name: "_auctionId",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_bidAmount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "joinSystemCoins",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_dst",
                type: "address",
                internalType: "address",
            },
            {
                name: "_wad",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "settleAuction",
        inputs: [
            {
                name: "_coinJoin",
                type: "address",
                internalType: "address",
            },
            {
                name: "_surplusAuctionHouse",
                type: "address",
                internalType: "address",
            },
            {
                name: "_auctionId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "error",
        name: "OnlyDelegateCalls",
        inputs: [],
    },
];
var ISurplusBidActions__factory = exports.ISurplusBidActions__factory = /** @class */ (function () {
    function ISurplusBidActions__factory() {
    }
    ISurplusBidActions__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ISurplusBidActions__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ISurplusBidActions__factory.abi = _abi;
    return ISurplusBidActions__factory;
}());
//# sourceMappingURL=ISurplusBidActions__factory.js.map