"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUniV3RelayerChild__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "baseAmount",
        inputs: [],
        outputs: [
            {
                name: "_baseAmount",
                type: "uint128",
                internalType: "uint128",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "baseToken",
        inputs: [],
        outputs: [
            {
                name: "_baseToken",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "factory",
        inputs: [],
        outputs: [
            {
                name: "_factory",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getResultWithValidity",
        inputs: [],
        outputs: [
            {
                name: "_result",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_validity",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "multiplier",
        inputs: [],
        outputs: [
            {
                name: "_multiplier",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "quotePeriod",
        inputs: [],
        outputs: [
            {
                name: "_quotePeriod",
                type: "uint32",
                internalType: "uint32",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "quoteToken",
        inputs: [],
        outputs: [
            {
                name: "_quoteToken",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "read",
        inputs: [],
        outputs: [
            {
                name: "_value",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [
            {
                name: "_symbol",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "uniV3Pool",
        inputs: [],
        outputs: [
            {
                name: "_uniV3Pool",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "error",
        name: "CallerNotFactory",
        inputs: [],
    },
    {
        type: "error",
        name: "InvalidPriceFeed",
        inputs: [],
    },
    {
        type: "error",
        name: "NotFactoryDeployment",
        inputs: [],
    },
    {
        type: "error",
        name: "UniV3Relayer_InvalidPool",
        inputs: [],
    },
];
var IUniV3RelayerChild__factory = exports.IUniV3RelayerChild__factory = /** @class */ (function () {
    function IUniV3RelayerChild__factory() {
    }
    IUniV3RelayerChild__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IUniV3RelayerChild__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IUniV3RelayerChild__factory.abi = _abi;
    return IUniV3RelayerChild__factory;
}());
//# sourceMappingURL=IUniV3RelayerChild__factory.js.map