"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IYearnVeloVaultRelayerFactory__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "addAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "authorizedAccounts",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "_authorized",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "authorizedAccounts",
        inputs: [],
        outputs: [
            {
                name: "_accounts",
                type: "address[]",
                internalType: "address[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "deployYearnVeloVaultRelayer",
        inputs: [
            {
                name: "_yearnVault",
                type: "address",
                internalType: "contract IYearnVault",
            },
            {
                name: "_veloPool",
                type: "address",
                internalType: "contract IVeloPool",
            },
            {
                name: "_veloLpOracle",
                type: "address",
                internalType: "contract IPessimisticVeloLpOracle",
            },
        ],
        outputs: [
            {
                name: "_yearnVeloVaultRelayer",
                type: "address",
                internalType: "contract IBaseOracle",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "yearnVeloVaultRelayersList",
        inputs: [],
        outputs: [
            {
                name: "_yearnVeloVaultRelayersList",
                type: "address[]",
                internalType: "address[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "AddAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "NewYearnVeloVaultRelayer",
        inputs: [
            {
                name: "_yearnVeloVaultRelayer",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "_yearnVault",
                type: "address",
                indexed: false,
                internalType: "address",
            },
            {
                name: "_veloPool",
                type: "address",
                indexed: false,
                internalType: "address",
            },
            {
                name: "_veloLpOracle",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RemoveAuthorization",
        inputs: [
            {
                name: "_account",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "AlreadyAuthorized",
        inputs: [],
    },
    {
        type: "error",
        name: "NotAuthorized",
        inputs: [],
    },
    {
        type: "error",
        name: "Unauthorized",
        inputs: [],
    },
];
var IYearnVeloVaultRelayerFactory__factory = exports.IYearnVeloVaultRelayerFactory__factory = /** @class */ (function () {
    function IYearnVeloVaultRelayerFactory__factory() {
    }
    IYearnVeloVaultRelayerFactory__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IYearnVeloVaultRelayerFactory__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IYearnVeloVaultRelayerFactory__factory.abi = _abi;
    return IYearnVeloVaultRelayerFactory__factory;
}());
//# sourceMappingURL=IYearnVeloVaultRelayerFactory__factory.js.map