"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockChainlinkFeed__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "constructor",
        inputs: [
            {
                name: "_desc",
                type: "string",
                internalType: "string",
            },
            {
                name: "_initialAnswer",
                type: "int256",
                internalType: "int256",
            },
            {
                name: "_initialDecimals",
                type: "uint8",
                internalType: "uint8",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "decimals",
        inputs: [],
        outputs: [
            {
                name: "_decimalsResult",
                type: "uint8",
                internalType: "uint8",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "description",
        inputs: [],
        outputs: [
            {
                name: "_desc",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoundData",
        inputs: [
            {
                name: "_roundId",
                type: "uint80",
                internalType: "uint80",
            },
        ],
        outputs: [
            {
                name: "_roundIdResult",
                type: "uint80",
                internalType: "uint80",
            },
            {
                name: "_answerResult",
                type: "int256",
                internalType: "int256",
            },
            {
                name: "_startedAtResult",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_updatedAtResult",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_answeredInRoundResult",
                type: "uint80",
                internalType: "uint80",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "latestRoundData",
        inputs: [],
        outputs: [
            {
                name: "_roundIdResult",
                type: "uint80",
                internalType: "uint80",
            },
            {
                name: "_answerResult",
                type: "int256",
                internalType: "int256",
            },
            {
                name: "_startedAtResult",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_updatedAtResult",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_answeredInRoundResult",
                type: "uint80",
                internalType: "uint80",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "setPrice",
        inputs: [
            {
                name: "_price",
                type: "int256",
                internalType: "int256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "version",
        inputs: [],
        outputs: [
            {
                name: "_version",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "pure",
    },
];
var MockChainlinkFeed__factory = exports.MockChainlinkFeed__factory = /** @class */ (function () {
    function MockChainlinkFeed__factory() {
    }
    MockChainlinkFeed__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    MockChainlinkFeed__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    MockChainlinkFeed__factory.abi = _abi;
    return MockChainlinkFeed__factory;
}());
//# sourceMappingURL=MockChainlinkFeed__factory.js.map