"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Parysproxyfactory__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "function",
        name: "build",
        inputs: [],
        outputs: [
            {
                name: "_proxy",
                type: "address",
                internalType: "address payable",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "build",
        inputs: [
            {
                name: "_owner",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "_proxy",
                type: "address",
                internalType: "address payable",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "isProxy",
        inputs: [
            {
                name: "_proxyAddress",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "_exists",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "nonces",
        inputs: [
            {
                name: "_owner",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "nonce",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "proxies",
        inputs: [
            {
                name: "_owner",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract IParysProxy",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "Created",
        inputs: [
            {
                name: "_sender",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "_owner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "_proxy",
                type: "address",
                indexed: false,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "AlreadyHasProxy",
        inputs: [
            {
                name: "_owner",
                type: "address",
                internalType: "address",
            },
            {
                name: "_proxy",
                type: "address",
                internalType: "contract IParysProxy",
            },
        ],
    },
];
var Parysproxyfactory__factory = exports.Parysproxyfactory__factory = /** @class */ (function () {
    function Parysproxyfactory__factory() {
    }
    Parysproxyfactory__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Parysproxyfactory__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Parysproxyfactory__factory.abi = _abi;
    return Parysproxyfactory__factory;
}());
//# sourceMappingURL=Parysproxyfactory__factory.js.map