"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Reentrancyguard__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
        inputs: [],
    },
];
var Reentrancyguard__factory = exports.Reentrancyguard__factory = /** @class */ (function () {
    function Reentrancyguard__factory() {
    }
    Reentrancyguard__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Reentrancyguard__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Reentrancyguard__factory.abi = _abi;
    return Reentrancyguard__factory;
}());
//# sourceMappingURL=Reentrancyguard__factory.js.map