"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SAFEHandler__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "constructor",
        inputs: [
            {
                name: "_safeEngine",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "nonpayable",
    },
];
var SAFEHandler__factory = exports.SAFEHandler__factory = /** @class */ (function () {
    function SAFEHandler__factory() {
    }
    SAFEHandler__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    SAFEHandler__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    SAFEHandler__factory.abi = _abi;
    return SAFEHandler__factory;
}());
//# sourceMappingURL=SAFEHandler__factory.js.map