"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.Shortstrings__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        type: "error",
        name: "InvalidShortString",
        inputs: [],
    },
    {
        type: "error",
        name: "StringTooLong",
        inputs: [
            {
                name: "str",
                type: "string",
                internalType: "string",
            },
        ],
    },
];
var Shortstrings__factory = exports.Shortstrings__factory = /** @class */ (function () {
    function Shortstrings__factory() {
    }
    Shortstrings__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    Shortstrings__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    Shortstrings__factory.abi = _abi;
    return Shortstrings__factory;
}());
//# sourceMappingURL=Shortstrings__factory.js.map