/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBeefyVeloVaultRelayerChild,
  IBeefyVeloVaultRelayerChildInterface,
} from "../IBeefyVeloVaultRelayerChild";

const _abi = [
  {
    type: "function",
    name: "beefyVault",
    inputs: [],
    outputs: [
      {
        name: "_beefyVault",
        type: "address",
        internalType: "contract IBeefyVaultV7",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "factory",
    inputs: [],
    outputs: [
      {
        name: "_factory",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getResultWithValidity",
    inputs: [],
    outputs: [
      {
        name: "_result",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_validity",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "read",
    inputs: [],
    outputs: [
      {
        name: "_value",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [
      {
        name: "_symbol",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "veloLpOracle",
    inputs: [],
    outputs: [
      {
        name: "_veloPool",
        type: "address",
        internalType: "contract IPessimisticVeloLpOracle",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "veloPool",
    inputs: [],
    outputs: [
      {
        name: "_veloPool",
        type: "address",
        internalType: "contract IVeloPool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "error",
    name: "AbstractVeloVaultRelayer_NullVeloLpOracle",
    inputs: [],
  },
  {
    type: "error",
    name: "AbstractVeloVaultRelayer_NullVeloPool",
    inputs: [],
  },
  {
    type: "error",
    name: "BeefyVeloVaultRelayer_InvalidPriceSource",
    inputs: [],
  },
  {
    type: "error",
    name: "BeefyVeloVaultRelayer_NullBeefyVault",
    inputs: [],
  },
  {
    type: "error",
    name: "CallerNotFactory",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidPriceFeed",
    inputs: [],
  },
  {
    type: "error",
    name: "NotFactoryDeployment",
    inputs: [],
  },
] as const;

export class IBeefyVeloVaultRelayerChild__factory {
  static readonly abi = _abi;
  static createInterface(): IBeefyVeloVaultRelayerChildInterface {
    return new Interface(_abi) as IBeefyVeloVaultRelayerChildInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBeefyVeloVaultRelayerChild {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IBeefyVeloVaultRelayerChild;
  }
}
