/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IVeloPool, IVeloPoolInterface } from "../IVeloPool";

const _abi = [
  {
    type: "function",
    name: "reserve0",
    inputs: [],
    outputs: [
      {
        name: "_reserve0",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "reserve1",
    inputs: [],
    outputs: [
      {
        name: "_reserve1",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [
      {
        name: "_symbol",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [
      {
        name: "_totalSupply",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class IVeloPool__factory {
  static readonly abi = _abi;
  static createInterface(): IVeloPoolInterface {
    return new Interface(_abi) as IVeloPoolInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVeloPool {
    return new Contract(address, _abi, runner) as unknown as IVeloPool;
  }
}
