"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Safe = void 0;
/**
 * This object represents a GEB safe. It has the entire SAFE state and provides helper functions to calculate its liquidation price, collateralization ratio etc.
 */
var Safe = /** @class */ (function () {
    function Safe(contracts, 
    /**
     * SAFE handler in the SAFE Engine
     */
    handler, 
    /**
     * Amount of debt generated by the SAFE (WAD)
     */
    debt, 
    /**
     * Amount of collateral locked in the SAFE (WAD)
     */
    collateral, 
    /**
     * SAFE collateral type
     */
    collateralType, 
    /**
     * Whether the safe was opened using a SAFE manager or not
     */
    isManaged, 
    /**
     * Safe incremental ID, only for managed safes
     */
    safeId) {
        this.contracts = contracts;
        this.handler = handler;
        this.debt = debt;
        this.collateral = collateral;
        this.collateralType = collateralType;
        this.isManaged = isManaged;
        this.safeId = safeId;
    }
    return Safe;
}());
exports.Safe = Safe;
//# sourceMappingURL=safe.js.map