/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DenominatedOracle,
  DenominatedOracleInterface,
} from "../DenominatedOracle";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_priceSource",
        type: "address",
        internalType: "contract IBaseOracle",
      },
      {
        name: "_denominationPriceSource",
        type: "address",
        internalType: "contract IBaseOracle",
      },
      {
        name: "_inverted",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "denominationPriceSource",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IBaseOracle",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getResultWithValidity",
    inputs: [],
    outputs: [
      {
        name: "_result",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_validity",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "inverted",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "priceSource",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IBaseOracle",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "read",
    inputs: [],
    outputs: [
      {
        name: "_result",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "error",
    name: "DenominatedOracle_NullPriceSource",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidPriceFeed",
    inputs: [],
  },
] as const;

export class DenominatedOracle__factory {
  static readonly abi = _abi;
  static createInterface(): DenominatedOracleInterface {
    return new utils.Interface(_abi) as DenominatedOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DenominatedOracle {
    return new Contract(address, _abi, signerOrProvider) as DenominatedOracle;
  }
}
