/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IChainlinkRelayer,
  IChainlinkRelayerInterface,
} from "../IChainlinkRelayer";

const _abi = [
  {
    type: "function",
    name: "getResultWithValidity",
    inputs: [],
    outputs: [
      {
        name: "_result",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_validity",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "multiplier",
    inputs: [],
    outputs: [
      {
        name: "_multiplier",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "priceFeed",
    inputs: [],
    outputs: [
      {
        name: "_priceFeed",
        type: "address",
        internalType: "contract IChainlinkOracle",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "read",
    inputs: [],
    outputs: [
      {
        name: "_value",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sequencerUptimeFeed",
    inputs: [],
    outputs: [
      {
        name: "_sequencerUptimeFeed",
        type: "address",
        internalType: "contract IChainlinkOracle",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "staleThreshold",
    inputs: [],
    outputs: [
      {
        name: "_staleThreshold",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [
      {
        name: "_symbol",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "error",
    name: "ChainlinkRelayer_NullPriceFeed",
    inputs: [],
  },
  {
    type: "error",
    name: "ChainlinkRelayer_NullSequencerUptimeFeed",
    inputs: [],
  },
  {
    type: "error",
    name: "ChainlinkRelayer_NullStaleThreshold",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidPriceFeed",
    inputs: [],
  },
] as const;

export class IChainlinkRelayer__factory {
  static readonly abi = _abi;
  static createInterface(): IChainlinkRelayerInterface {
    return new utils.Interface(_abi) as IChainlinkRelayerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainlinkRelayer {
    return new Contract(address, _abi, signerOrProvider) as IChainlinkRelayer;
  }
}
