/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { SAFEHandler, SAFEHandlerInterface } from "../SAFEHandler";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_safeEngine",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
] as const;

export class SAFEHandler__factory {
  static readonly abi = _abi;
  static createInterface(): SAFEHandlerInterface {
    return new utils.Interface(_abi) as SAFEHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SAFEHandler {
    return new Contract(address, _abi, signerOrProvider) as SAFEHandler;
  }
}
