/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  UniV3RelayerFactory,
  UniV3RelayerFactoryInterface,
} from "../UniV3RelayerFactory";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_uniV3Factory",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addAuthorization",
    inputs: [
      {
        name: "_account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "authorizedAccounts",
    inputs: [
      {
        name: "_account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "_authorized",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedAccounts",
    inputs: [],
    outputs: [
      {
        name: "_accounts",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deployUniV3Relayer",
    inputs: [
      {
        name: "_baseToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "_quoteToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "_feeTier",
        type: "uint24",
        internalType: "uint24",
      },
      {
        name: "_quotePeriod",
        type: "uint32",
        internalType: "uint32",
      },
    ],
    outputs: [
      {
        name: "_uniV3Relayer",
        type: "address",
        internalType: "contract IBaseOracle",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeAuthorization",
    inputs: [
      {
        name: "_account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "uniV3RelayersList",
    inputs: [],
    outputs: [
      {
        name: "_uniV3RelayersList",
        type: "address[]",
        internalType: "address[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AddAuthorization",
    inputs: [
      {
        name: "_account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NewUniV3Relayer",
    inputs: [
      {
        name: "_uniV3Relayer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "_baseToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_quoteToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "_feeTier",
        type: "uint24",
        indexed: false,
        internalType: "uint24",
      },
      {
        name: "_quotePeriod",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemoveAuthorization",
    inputs: [
      {
        name: "_account",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AlreadyAuthorized",
    inputs: [],
  },
  {
    type: "error",
    name: "NotAuthorized",
    inputs: [],
  },
  {
    type: "error",
    name: "Unauthorized",
    inputs: [],
  },
] as const;

export class UniV3RelayerFactory__factory {
  static readonly abi = _abi;
  static createInterface(): UniV3RelayerFactoryInterface {
    return new utils.Interface(_abi) as UniV3RelayerFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UniV3RelayerFactory {
    return new Contract(address, _abi, signerOrProvider) as UniV3RelayerFactory;
  }
}
