/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { UniV3Relayer, UniV3RelayerInterface } from "../UniV3Relayer";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_uniV3Factory",
        type: "address",
        internalType: "address",
      },
      {
        name: "_baseToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "_quoteToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "_feeTier",
        type: "uint24",
        internalType: "uint24",
      },
      {
        name: "_quotePeriod",
        type: "uint32",
        internalType: "uint32",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "baseAmount",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint128",
        internalType: "uint128",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseToken",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getResultWithValidity",
    inputs: [],
    outputs: [
      {
        name: "_result",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_validity",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "multiplier",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quotePeriod",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint32",
        internalType: "uint32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quoteToken",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "read",
    inputs: [],
    outputs: [
      {
        name: "_result",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "string",
        internalType: "string",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "uniV3Pool",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "error",
    name: "InvalidPriceFeed",
    inputs: [],
  },
  {
    type: "error",
    name: "UniV3Relayer_InvalidPool",
    inputs: [],
  },
] as const;

export class UniV3Relayer__factory {
  static readonly abi = _abi;
  static createInterface(): UniV3RelayerInterface {
    return new utils.Interface(_abi) as UniV3RelayerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UniV3Relayer {
    return new Contract(address, _abi, signerOrProvider) as UniV3Relayer;
  }
}
